## Course Assignment Instructions
You should have Python (version 3.8 or later) and Jupyter Notebook installed to complete this assignment. You will write code in the empty cell/cells below the problem. While most of this will be a programming assignment, some questions will ask you to "write a few sentences" in markdown cells. 

Submission Instructions:

Create a labs directory in your personal class repository (e.g., located in your home directory)
Clone the class repository
Copy this Jupyter notebook file (.ipynb) into your repo/labs directory
Make your edits, commit changes, and push to your repository
All submissions must be pushed before the due date to avoid late penalties

* Install the numpy, scipy, statsmodels, and pandas packages (we will be using these throughout the semester)

In [5]:
%pip install numpy scipy statsmodels pandas

Note: you may need to restart the kernel to use updated packages.


* Print out the numerical constant pi with ten digits after the decimal point using constant 'pi'. You will need to use the math module in python for this. 

In [7]:
import math

print(math.pi)
print(round(math.pi, 10)) # 10 decimal place

3.141592653589793
3.1415926536


* Sum up the first 103 terms of the series 1 + 1/2 + 1/4 + 1/8 + ... use base python

In [9]:
sum = 0

for i in range(103):
    sum += 1 / (2**i)

print(sum)



2.0


In [10]:
del(sum)

In [11]:
sum(1/(2**i) for i in range(103))

2.0

using numpy

In [13]:
import numpy as np

total = np.sum(1/(2**i) for i in np.arange(103))

print(total)

inf


/var/folders/02/jg9_m6811jsf3kzckqrtm9080000gn/T/ipykernel_37016/3755685867.py:3: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  total = np.sum(1/(2**i) for i in np.arange(103))
/var/folders/02/jg9_m6811jsf3kzckqrtm9080000gn/T/ipykernel_37016/3755685867.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  total = np.sum(1/(2**i) for i in np.arange(103))


 * The issue here arises because NumPy's 2 ** np.arange(103) may overflow for very large exponents, leading to incorrect results. NumPy uses fixed-precision data types, which can cause problems when dealing with extremely large numbers.  * The issue here arises because NumPy's 2 ** np.arange(103) may overflow for very large exponents, leading to incorrect results. NumPy uses fixed-precision data types, which can cause problems when dealing with extremely large numbers.

In [15]:
total = np.sum(1/(2.0**i) for i in np.arange(103))

print(total)

2.0


/var/folders/02/jg9_m6811jsf3kzckqrtm9080000gn/T/ipykernel_37016/132187091.py:1: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  total = np.sum(1/(2.0**i) for i in np.arange(103))


* Find the product of the first 387 terms of `1 * 1/2 * 1/4 * 1/8 *` ...

using base python

In [18]:
product = 1

for i in range(387):
    product *= 1/ ( 2 ** i)

print(product)

0.0


using numpy

In [20]:
num = np.product(1/(2.0** np.arange(387)))
print(num)

0.0


Is this answer *exactly* correct?

No, this answer is not exactly correct. The number should be positive although very small and the answer generated is a result of numerical underflow.

* Figure out a means to express the answer more exactly. Not compute exactly, but express more exactly.

In [23]:
import math as m

-m.log(2) * sum(range(387))

-51771.856063202875

* using numpy ... Hint: use the `log` and `sum` functions in numpy

In [25]:
-np.log(2) * np.sum(np.arange(387))

-51771.856063202875

* Create the sequence `x = [Inf, 20, 18, ..., -20]`.

Pure python

In [28]:
# Create the sequence
x = [float('inf')] + list(range(20, -22, -2))

# Print the result
print(x)

[inf, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0, -2, -4, -6, -8, -10, -12, -14, -16, -18, -20]


Using numpy

In [30]:
# Create the sequence
x = [float('inf')] + list(np.arange(20, -22, -2))

# Print the result
print(x)

[inf, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0, -2, -4, -6, -8, -10, -12, -14, -16, -18, -20]


*   Create the sequence `x = [log_3(Inf), log_3(100), log_3(98), ... log_3(-20)]` ... Use `log` from numpy.

In [32]:
# Create the sequence
seq =  [float('inf')] + list(range(100, -21, -2))

# Compute the base-3 logarithm
x = np.log(seq) / np.log(3)

    
print(x)

[       inf 4.19180655 4.17341725 4.15464877 4.13548513 4.11590934
 4.09590327 4.0754476  4.05452164 4.03310326 4.01116872 3.98869254
 3.96564727 3.94200337 3.91772888 3.89278926 3.86714702 3.84076143
 3.81358809 3.78557852 3.75667961 3.72683303 3.69597451 3.66403301
 3.63092975 3.59657703 3.5608768  3.52371901 3.48497958 3.44451785
 3.4021735  3.35776278 3.31107361 3.26185951 3.20983168 3.15464877
 3.09590327 3.03310326 2.96564727 2.89278926 2.81358809 2.72683303
 2.63092975 2.52371901 2.4021735  2.26185951 2.09590327 1.89278926
 1.63092975 1.26185951 0.63092975       -inf        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan]


/var/folders/02/jg9_m6811jsf3kzckqrtm9080000gn/T/ipykernel_37016/1085755462.py:5: RuntimeWarning: divide by zero encountered in log
  x = np.log(seq) / np.log(3)
/var/folders/02/jg9_m6811jsf3kzckqrtm9080000gn/T/ipykernel_37016/1085755462.py:5: RuntimeWarning: invalid value encountered in log
  x = np.log(seq) / np.log(3)


* Create a vector of booleans where the entry is true if `x[i]` is positive and finite. Use `&` from base python along with `isnan` and `isinfinite` from numpy

In [34]:
# x = np.array(x)
y = ~np.isnan(x) & np.isfinite(x) & (x > 0)

print(y)

[False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False False False False False
 False False]


* Locate the indices of the non-real numbers in this vector. Numpy has a `where` function in lieu of R's `which`

In [36]:
false_indices = np.where(y== False)[0]
print(false_indices)

[ 0 51 52 53 54 55 56 57 58 59 60 61]


* Locate the indices of the infinite quantities in this vector using `where` and `isinf` from numpy.

In [38]:
np.where(np.isinf(x))[0]

array([ 0, 51])

* Locate the indices of the min and max in this vector. Hint: use the `arg.min` and `arg.max` functions from numpy

In [40]:

xs = [i for i in x if (~np.isnan(i))]
#print(xs)
r = [np.argmax(xs), np.argmin(xs)]

print(r)

[0, 51]


* Count the number of unique values in `x`. Use `unique` from numpy.

In [42]:
len(np.unique(x))

53

* Cast `x` to a factor. Do the number of levels make sense? Should be 53 unique values. Use `categorical` from pandas.

In [44]:
import pandas as pd

# Cast x to a categorical (similar to as.factor(x) in R)
x_factor = pd.Categorical(x)

# Check the unique levels (categories)
levels = x_factor.categories
num_levels = len(levels)

print(f"Factor levels: {levels}")
print(f"Number of levels: {num_levels}")

Factor levels: Index([              -inf, 0.6309297535714574, 1.2618595071429148,
       1.6309297535714573,  1.892789260714372,  2.095903274289385,
       2.2618595071429146,  2.402173502732879, 2.5237190142858297,
        2.630929753571457, 2.7268330278608417, 2.8135880922155954,
       2.8927892607143724,   2.96564727304425,  3.033103256304337,
       3.0959032742893844,  3.154648767857287, 3.2098316767340234,
       3.2618595071429146, 3.3110736128178324,  3.357762781432299,
       3.4021735027328797, 3.4445178457870527, 3.4849795837717283,
       3.5237190142858297, 3.5608767950073115, 3.5965770266157073,
       3.6309297535714573, 3.6640330098757947, 3.6959745056821194,
       3.7268330278608417,  3.756679610828472,  3.785578521428744,
        3.813588092215595, 3.8407614303054807, 3.8671470234508067,
        3.892789260714372, 3.9177288817897304, 3.9420033663892897,
       3.9656472730442496, 3.9886925350037563,  4.011168719591413,
       4.0331032563043365, 4.0545216380691365, 

* In Python, using pandas, NaN is not treated as a level in a categorical type by default. Pandas does not allow NaN to be a category. To include NaN as a level, you need to explicitly handle it by filling them with a placeholder value (like "NaN" or a specific number) before making the data categorical. Use `categorical` and `isna` from pandas.

In [46]:
# Replace NaN with a placeholder value (e.g., 'NaN')
x_filled = [val if not pd.isna(val) else 'NaN' for val in x] # list comprihension

# Convert to categorical
x_factor = pd.Categorical(x_filled)

# Check the unique levels (including 'NaN' as a level)
factor_levels = x_factor.categories
num_levels = len(factor_levels)

print(f"Factor levels (including NaN): {factor_levels}")
print(f"Number of levels: {num_levels}")

Factor levels (including NaN): Index([              -inf, 0.6309297535714574, 1.2618595071429148,
       1.6309297535714573,  1.892789260714372,  2.095903274289385,
       2.2618595071429146,  2.402173502732879, 2.5237190142858297,
        2.630929753571457, 2.7268330278608417, 2.8135880922155954,
       2.8927892607143724,   2.96564727304425,  3.033103256304337,
       3.0959032742893844,  3.154648767857287, 3.2098316767340234,
       3.2618595071429146, 3.3110736128178324,  3.357762781432299,
       3.4021735027328797, 3.4445178457870527, 3.4849795837717283,
       3.5237190142858297, 3.5608767950073115, 3.5965770266157073,
       3.6309297535714573, 3.6640330098757947, 3.6959745056821194,
       3.7268330278608417,  3.756679610828472,  3.785578521428744,
        3.813588092215595, 3.8407614303054807, 3.8671470234508067,
        3.892789260714372, 3.9177288817897304, 3.9420033663892897,
       3.9656472730442496, 3.9886925350037563,  4.011168719591413,
       4.0331032563043365, 4.05

* Cast `x` to integers. Use `where`, `isfinite` from numpy and `astype` from base python.

In [48]:
replaced_inf_x = np.where(np.isfinite(x), x,0) 
# replaced_inf_x
int_x = replaced_inf_x.astype(int)
print(int_x)


[0 4 4 4 4 4 4 4 4 4 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 2 2 2 2 2 2 2 2 2 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]


* Use `x` to create a new vector `y` containing only the real numbers in x. Use `isnan`, `logical_and`, and `reduce` from numpy

In [50]:
y = x[np.logical_and.reduce((~np.isnan(x),np.isfinite(x), x > 0))]
print(y)

[4.19180655 4.17341725 4.15464877 4.13548513 4.11590934 4.09590327
 4.0754476  4.05452164 4.03310326 4.01116872 3.98869254 3.96564727
 3.94200337 3.91772888 3.89278926 3.86714702 3.84076143 3.81358809
 3.78557852 3.75667961 3.72683303 3.69597451 3.66403301 3.63092975
 3.59657703 3.5608768  3.52371901 3.48497958 3.44451785 3.4021735
 3.35776278 3.31107361 3.26185951 3.20983168 3.15464877 3.09590327
 3.03310326 2.96564727 2.89278926 2.81358809 2.72683303 2.63092975
 2.52371901 2.4021735  2.26185951 2.09590327 1.89278926 1.63092975
 1.26185951 0.63092975]


* Use the left rectangle method to numerically integrate x^2 from 0 to 1 with rectangle width size 1e-6. Use `arrange` and `sum` from numpy

In [52]:
# Define the rectangle width
width = 1e-6

# Create the sequence for the left endpoints (similar to seq in R)
x = np.arange(0, 1, width)

# Compute the sum using the left rectangle method
approximation = np.sum(x ** 2) * width

# Print the result
print(approximation)


0.33333283333349994


* Calculate the average of 100 realizations of standard Bernoullis in one line using the numpy's random.choice function.

In [54]:
mean_bern = np.mean(np.random.choice([0,1], size = 100, replace=True))
mean_bern

0.53

* Calculate the average of 500 realizations of Bernoullis with p = 0.9 in one line using the `random.choice` and `mean` functions in numpy.

In [56]:
mean_bern2 = np.mean(np.random.choice([0,1],p=[0.1,0.9], size = 500, replace=True))
mean_bern2

0.9

* Calculate the average of 1000 realizations of Bernoullis with p = 0.9 in one line using `binom` from scipy.stats.

In [59]:
from scipy.stats import binom
binom.rvs(n=1,p=0.9,size=1000).mean()

0.883

* Let `n = 50`. Create a n x n matrix `R` of exactly 50% entries 0's, 25% 1's 25% 2's. These values should be in random locations.

In [61]:
import pandas as pd

# Set n
n = 50

# Generate the random values with specified proportions
values = np.random.permutation(
    np.concatenate([
        np.full(int(n * n * 0.5), 0),  # 50% 0's
        np.full(int(n * n * 0.25), 1), # 25% 1's
        np.full(int(n * n * 0.25), 2)  # 25% 2's
    ])
)

# Reshape the values into an n x n matrix
R = values.reshape(n, n)

# Convert the matrix into a DataFrame
df = pd.DataFrame(R)

# Print the DataFrame
print(df)

    0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
0    1   1   0   0   0   1   1   0   0   0  ...   0   2   0   0   0   0   0   
1    0   0   0   0   0   0   2   0   0   0  ...   0   1   1   0   2   0   2   
2    0   0   1   1   1   0   2   2   0   0  ...   2   0   0   0   0   2   1   
3    0   0   0   0   2   2   0   0   0   0  ...   0   1   0   1   0   0   0   
4    0   1   1   0   2   2   1   2   1   0  ...   2   0   2   2   1   2   0   
5    2   0   0   1   1   2   0   0   0   2  ...   2   0   1   0   1   1   2   
6    1   1   0   2   0   0   1   0   0   0  ...   1   0   0   2   0   0   0   
7    2   2   0   0   0   2   2   0   0   2  ...   0   1   0   2   0   0   2   
8    2   0   2   2   2   2   2   2   0   0  ...   2   0   0   0   1   0   0   
9    1   1   0   0   0   1   1   0   2   1  ...   0   0   1   0   1   2   2   
10   0   0   2   0   2   0   0   0   0   1  ...   0   2   2   0   2   0   2   
11   0   0   2   1   1   1   0   2   0   0  ...   1 

* Randomly punch holes (i.e. `NA`) values in this matrix so that an each entry is missing with probability 30%.

In [63]:
# Convert to float to allow NaN
df = df.astype(float)

# Randomly punch holes with 30% probability
mask = np.random.choice([True, False], size=df.shape, p=[0.3, 0.7])
df[mask] = np.nan

# View the resulting DataFrame
print(df)

     0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   1.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  NaN  0.0  ...  0.0  NaN  NaN  0.0   
1   NaN  0.0  0.0  NaN  0.0  0.0  2.0  NaN  0.0  0.0  ...  0.0  1.0  NaN  0.0   
2   NaN  0.0  1.0  1.0  1.0  NaN  2.0  2.0  NaN  0.0  ...  NaN  NaN  0.0  NaN   
3   NaN  0.0  0.0  0.0  2.0  2.0  NaN  0.0  0.0  0.0  ...  NaN  1.0  0.0  1.0   
4   0.0  NaN  1.0  0.0  2.0  2.0  1.0  NaN  1.0  0.0  ...  2.0  0.0  2.0  NaN   
5   2.0  0.0  0.0  1.0  1.0  2.0  0.0  NaN  0.0  NaN  ...  NaN  0.0  NaN  0.0   
6   1.0  1.0  0.0  2.0  0.0  0.0  1.0  0.0  NaN  0.0  ...  1.0  NaN  0.0  2.0   
7   2.0  NaN  0.0  NaN  0.0  NaN  NaN  NaN  0.0  2.0  ...  0.0  1.0  0.0  2.0   
8   2.0  NaN  NaN  2.0  2.0  2.0  NaN  NaN  0.0  0.0  ...  2.0  0.0  0.0  0.0   
9   1.0  1.0  NaN  0.0  NaN  1.0  NaN  NaN  NaN  NaN  ...  0.0  0.0  NaN  0.0   
10  0.0  0.0  2.0  NaN  2.0  0.0  NaN  0.0  0.0  1.0  ...  0.0  2.0  2.0  0.0   
11  0.0  NaN  2.0  1.0  1.0 

In [64]:
import numpy as np
import pandas as pd

# Set matrix dimensions and proportions
n = 50
values = np.random.permutation(
    np.concatenate([
        np.full(int(n * n * 0.5), 0),  # 50% 0's
        np.full(int(n * n * 0.25), 1), # 25% 1's
        np.full(int(n * n * 0.25), 2)  # 25% 2's
    ])
)

# Reshape the matrix
R = values.reshape(n, n)

# Create a mask for punching holes with a 30% probability
random_holes = np.random.choice([True, False], size=(n, n), p=[0.3, 0.7])

# Assign NaN to the corresponding positions
R = R.astype(float)  # Convert to float to support NaN
R[random_holes] = np.nan

# Convert to DataFrame
df = pd.DataFrame(R)


print(df)


     0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   NaN  NaN  NaN  NaN  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  NaN  NaN   
1   0.0  1.0  NaN  NaN  0.0  0.0  NaN  1.0  2.0  NaN  ...  1.0  0.0  NaN  NaN   
2   2.0  0.0  NaN  NaN  NaN  2.0  NaN  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3   0.0  0.0  NaN  0.0  1.0  2.0  2.0  NaN  NaN  1.0  ...  1.0  2.0  2.0  2.0   
4   NaN  2.0  1.0  2.0  NaN  1.0  NaN  NaN  0.0  NaN  ...  0.0  2.0  2.0  0.0   
5   2.0  NaN  0.0  1.0  1.0  0.0  0.0  2.0  NaN  0.0  ...  NaN  NaN  2.0  2.0   
6   NaN  2.0  0.0  2.0  NaN  NaN  0.0  1.0  2.0  1.0  ...  0.0  NaN  1.0  0.0   
7   2.0  1.0  2.0  1.0  2.0  2.0  2.0  0.0  2.0  NaN  ...  0.0  NaN  0.0  1.0   
8   0.0  NaN  0.0  1.0  NaN  0.0  0.0  0.0  NaN  NaN  ...  NaN  NaN  2.0  2.0   
9   1.0  0.0  0.0  NaN  NaN  2.0  NaN  1.0  NaN  2.0  ...  2.0  NaN  0.0  0.0   
10  0.0  1.0  2.0  1.0  NaN  2.0  NaN  0.0  0.0  NaN  ...  NaN  0.0  0.0  2.0   
11  0.0  2.0  1.0  NaN  NaN 

* Sort the rows in matrix `R` by the largest row sum to lowest. Be careful about the NA's!

In [66]:
# compute row sums, ignoring nan value
row_sum = np.nansum(R, axis =1)
print(row_sum)

# get the row indices sorted by largest row sum to lowest
sorted_by_row = np.argsort(row_sum)
print(sorted_by_row)

[14. 24. 16. 34. 34. 31. 34. 33. 24. 26. 23. 19. 25. 27. 26. 22. 30. 25.
 30. 25. 25. 36. 27. 32. 24. 22. 21. 31. 20. 44. 19. 20. 22. 31. 20. 35.
 27. 18. 29. 22. 14. 31. 24. 18. 37. 20. 27. 29. 19. 26.]
[ 0 40  2 43 37 30 11 48 34 31 45 28 26 25 15 39 32 10 42 24  8  1 19 12
 17 20 49 14  9 46 13 22 36 47 38 18 16 33  5 41 27 23  7  6  4  3 35 21
 44 29]


* Python does not have an apply function. Instead use the nanstd function in numpy to calculate the standard devation of each column. Print them and combine then into a dataframe.

In [68]:
# compute row wise and column wise standard deviation
# axis 1 is row
row_sd = np.nanstd(R, axis = 1)
col_sd = np.nanstd(R, axis = 0)

# combine the results into dictionary
result = {"row_sd": row_sd.tolist(), "col_sd": col_sd.tolist()}

result

{'row_sd': [0.669991708074726,
  0.8691737796972566,
  0.6384330708658226,
  0.869860611782262,
  0.8204451193747313,
  0.82015429110899,
  0.8204451193747313,
  0.7980985437964,
  0.82915619758885,
  0.8441447440717649,
  0.7510281019219874,
  0.8050858744917355,
  0.7772268862134539,
  0.8971610553204332,
  0.8065476000471817,
  0.831030832699942,
  0.7637626158259733,
  0.8359147460141363,
  0.8666143364630343,
  0.7787177820513957,
  0.7772268862134539,
  0.8298826628866154,
  0.7592027982620249,
  0.8607525202662151,
  0.8312321759177501,
  0.7680128579652817,
  0.7949493345141213,
  0.8867160944173538,
  0.7360580485752194,
  0.9245946589975047,
  0.7083668477301427,
  0.7714633558002354,
  0.8601138984851641,
  0.8216777476527244,
  0.8631669780812679,
  0.8365290562455222,
  0.8268680292312623,
  0.7317856271351827,
  0.8446711713768276,
  0.8258927081843614,
  0.7180219742846006,
  0.8749603165604458,
  0.816496580927726,
  0.7211710304933154,
  0.8867537312753727,
  0.7395099

* combine the results from the previous cell into a dataframe

In [70]:
sd_df = pd.DataFrame({"row_sd": row_sd.tolist(), "col_sd": col_sd.tolist()})
sd_df

row_sd    col_sd
0   0.669992  0.844671
1   0.869174  0.817537
2   0.638433  0.844145
3   0.869861  0.829883
4   0.820445  0.806548
5   0.820154  0.868408
6   0.820445  0.839825
7   0.798099  0.710585
8   0.829156  0.816497
9   0.844145  0.833268
10  0.751028  0.866525
11  0.805086  0.832594
12  0.777227  0.879986
13  0.897161  0.742636
14  0.806548  0.878898
15  0.831031  0.796293
16  0.763763  0.807097
17  0.835915  0.684935
18  0.866614  0.790158
19  0.778718  0.819890
20  0.777227  0.874442
21  0.829883  0.866025
22  0.759203  0.652385
23  0.860753  0.660699
24  0.831232  0.785407
25  0.768013  0.744118
26  0.794949  0.932404
27  0.886716  0.817620
28  0.736058  0.809668
29  0.924595  0.775294
30  0.708367  0.853879
31  0.771463  0.847215
32  0.860114  0.854670
33  0.821678  0.686623
34  0.863167  0.768779
35  0.836529  0.918027
36  0.826868  0.872494
37  0.731786  0.727060
38  0.844671  0.749970
39  0.825893  0.763763
40  0.718022  0.859995
41  0.874960  0.676216
42  0.816497  0.882266
43  0.721171  0.895570
44  0.886754  0.881671
45  0.739510  0.857469
46  0.757694  0.839222
47  0.843914  0.722128
48  0.755479  0.836286
49  0.837029  0.795908

* Use the Pandas apply function to compute a vector whose entries are the count of entries that are 1 or 2 in each column

In [72]:
R = pd.DataFrame(R)

# Compute the count of 1's and 2's in each column
counts = R.apply(lambda col: ((col == 1) | (col == 2)).sum(), axis=0)

# Print the counts
print(counts)


0     19
1     15
2     17
3     23
4     18
5     24
6     11
7     16
8     12
9     18
10    19
11    22
12    19
13    15
14    18
15    19
16    18
17    16
18    13
19    21
20    14
21    19
22    13
23    14
24    15
25    14
26    15
27    17
28    19
29    21
30    16
31    20
32    20
33    15
34    13
35    19
36    20
37    17
38    21
39    10
40    14
41    18
42    21
43    18
44    13
45    16
46    23
47    21
48    19
49    19
dtype: int64


Since we just switched between Pandas dataframes and Numpy arrays. Here are some handy ways to check to see if you are working with a Pandas dataframe or a Numpy array

In [74]:
# Check type directly
if type(R) == pd.DataFrame:
    print("R is a Pandas DataFrame")

if type(R) == np.ndarray:
    print("R is a NumPy array")

R is a Pandas DataFrame


In [75]:
# isinstance(object, classinfo): This function checks if an object is an instance of a specified class or subclass.
# function utilizing this function to check
def check_type(R):
    if isinstance(R, pd.DataFrame):
        return "Pandas DataFrame"
    elif isinstance(R, np.ndarray):
        return "NumPy array"
    else:
        return "Unknown type"

# Test the function
print(check_type(R))  # Output: Pandas DataFrame

Pandas DataFrame


* Create a list whose keys are the column number and values are the vector of the columns.

In [77]:

df = pd.DataFrame(R)

# Convert columns into a dictionary
col_dict = {i: df.iloc[:, i].tolist() for i in range(df.shape[1])}

print(col_dict)

{0: [nan, 0.0, 2.0, 0.0, nan, 2.0, nan, 2.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2.0, nan, nan, 1.0, 0.0, 1.0, 1.0, 1.0, 2.0, 0.0, 0.0, 2.0, 1.0, nan, 0.0, nan, 2.0, 0.0, nan, 2.0, 0.0, 2.0, 2.0, nan, nan, nan, nan, 0.0, nan, nan, 1.0, 1.0, 1.0, 0.0, 0.0, nan, 0.0], 1: [nan, 1.0, 0.0, 0.0, 2.0, nan, 2.0, 1.0, nan, 0.0, 1.0, 2.0, 1.0, nan, nan, nan, 1.0, nan, 1.0, 0.0, nan, nan, 0.0, nan, nan, 1.0, 0.0, 2.0, 2.0, 0.0, 0.0, 0.0, nan, nan, nan, 1.0, 0.0, 2.0, nan, 0.0, nan, 2.0, 0.0, nan, nan, 0.0, nan, nan, nan, nan], 2: [nan, nan, nan, nan, 1.0, 0.0, 0.0, 2.0, 0.0, 0.0, 2.0, 1.0, 2.0, nan, 0.0, 1.0, 0.0, 2.0, nan, 1.0, 0.0, 0.0, 0.0, nan, 2.0, 0.0, 0.0, 1.0, nan, 1.0, nan, 0.0, nan, 0.0, nan, 1.0, nan, 2.0, 1.0, nan, 2.0, nan, 0.0, nan, 2.0, nan, nan, 2.0, 0.0, 0.0], 3: [nan, nan, nan, 0.0, 2.0, 1.0, 2.0, 1.0, 1.0, nan, 1.0, nan, 2.0, nan, nan, nan, 1.0, 0.0, 2.0, nan, 2.0, 2.0, 0.0, nan, 2.0, 0.0, 1.0, nan, 0.0, 2.0, nan, nan, 2.0, 2.0, nan, 1.0, 1.0, 0.0, nan, 2.0, 0.0, 0.0, 0.0, 1.0, 2.0, 0.0, 

* Create a list whose keys are the column number and values are themselves a list with keys: "min" whose value is the minimum of the column, "max" whose value is the maximum of the column, "pct_missing" is the proportion of missingness in the column and "first_NA" whose value is the row number of the first time the NA appears. In R this was accomplished using lappy. In Python we will use dictionary comprehension in tandem with Numpy and Pandas operations.

In [79]:
df

0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   NaN  NaN  NaN  NaN  1.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  NaN  NaN   
1   0.0  1.0  NaN  NaN  0.0  0.0  NaN  1.0  2.0  NaN  ...  1.0  0.0  NaN  NaN   
2   2.0  0.0  NaN  NaN  NaN  2.0  NaN  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3   0.0  0.0  NaN  0.0  1.0  2.0  2.0  NaN  NaN  1.0  ...  1.0  2.0  2.0  2.0   
4   NaN  2.0  1.0  2.0  NaN  1.0  NaN  NaN  0.0  NaN  ...  0.0  2.0  2.0  0.0   
5   2.0  NaN  0.0  1.0  1.0  0.0  0.0  2.0  NaN  0.0  ...  NaN  NaN  2.0  2.0   
6   NaN  2.0  0.0  2.0  NaN  NaN  0.0  1.0  2.0  1.0  ...  0.0  NaN  1.0  0.0   
7   2.0  1.0  2.0  1.0  2.0  2.0  2.0  0.0  2.0  NaN  ...  0.0  NaN  0.0  1.0   
8   0.0  NaN  0.0  1.0  NaN  0.0  0.0  0.0  NaN  NaN  ...  NaN  NaN  2.0  2.0   
9   1.0  0.0  0.0  NaN  NaN  2.0  NaN  1.0  NaN  2.0  ...  2.0  NaN  0.0  0.0   
10  0.0  1.0  2.0  1.0  NaN  2.0  NaN  0.0  0.0  NaN  ...  NaN  0.0  0.0  2.0   
11  0.0  2.0  1.0  NaN  NaN  0.0  NaN  0.0  2.0  NaN  ...  0.0  NaN  NaN  0.0   
12  0.0  1.0  2.0  2.0  0.0  2.0  0.0  0.0  NaN  1.0  ...  NaN  1.0  1.0  2.0   
13  2.0  NaN  NaN  NaN  2.0  0.0  1.0  2.0  0.0  0.0  ...  NaN  1.0  NaN  NaN   
14  NaN  NaN  0.0  NaN  2.0  2.0  1.0  NaN  0.0  NaN  ...  NaN  0.0  1.0  2.0   
15  NaN  NaN  1.0  NaN  1.0  NaN  0.0  0.0  0.0  2.0  ...  0.0  0.0  0.0  NaN   
16  1.0  1.0  0.0  1.0  1.0  0.0  NaN  2.0  NaN  2.0  ...  NaN  NaN  NaN  2.0   
17  0.0  NaN  2.0  0.0  0.0  0.0  0.0  0.0  1.0  NaN  ...  0.0  0.0  0.0  0.0   
18  1.0  1.0  NaN  2.0  0.0  2.0  NaN  NaN  0.0  0.0  ...  0.0  NaN  0.0  0.0   
19  1.0  0.0  1.0  NaN  0.0  0.0  NaN  0.0  NaN  2.0  ...  NaN  0.0  0.0  0.0   
20  1.0  NaN  0.0  2.0  NaN  1.0  1.0  0.0  0.0  1.0  ...  2.0  0.0  2.0  NaN   
21  2.0  NaN  0.0  2.0  2.0  NaN  0.0  0.0  2.0  1.0  ...  0.0  NaN  2.0  NaN   
22  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  NaN  ...  NaN  1.0  0.0  2.0   
23  0.0  NaN  NaN  NaN  2.0  1.0  0.0  0.0  NaN  2.0  ...  1.0  1.0  NaN  1.0   
24  2.0  NaN  2.0  2.0  NaN  0.0  NaN  1.0  NaN  NaN  ...  0.0  1.0  2.0  0.0   
25  1.0  1.0  0.0  0.0  NaN  0.0  NaN  0.0  NaN  2.0  ...  NaN  0.0  0.0  0.0   
26  NaN  0.0  0.0  1.0  0.0  1.0  0.0  1.0  NaN  NaN  ...  2.0  0.0  NaN  NaN   
27  0.0  2.0  1.0  NaN  1.0  1.0  NaN  1.0  NaN  0.0  ...  0.0  1.0  0.0  2.0   
28  NaN  2.0  NaN  0.0  1.0  NaN  2.0  1.0  NaN  0.0  ...  0.0  NaN  0.0  0.0   
29  2.0  0.0  1.0  2.0  0.0  1.0  2.0  2.0  2.0  0.0  ...  2.0  1.0  0.0  2.0   
30  0.0  0.0  NaN  NaN  2.0  0.0  0.0  NaN  NaN  1.0  ...  NaN  1.0  1.0  0.0   
31  NaN  0.0  0.0  NaN  2.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  2.0  0.0   
32  2.0  NaN  NaN  2.0  0.0  1.0  NaN  0.0  NaN  0.0  ...  0.0  0.0  NaN  NaN   
33  0.0  NaN  0.0  2.0  0.0  NaN  0.0  2.0  NaN  NaN  ...  1.0  NaN  1.0  1.0   
34  2.0  NaN  NaN  NaN  0.0  2.0  0.0  0.0  1.0  0.0  ...  0.0  1.0  0.0  NaN   
35  2.0  1.0  1.0  1.0  1.0  2.0  NaN  0.0  0.0  NaN  ...  0.0  0.0  2.0  1.0   
36  NaN  0.0  NaN  1.0  2.0  0.0  0.0  0.0  0.0  2.0  ...  2.0  1.0  1.0  2.0   
37  NaN  2.0  2.0  0.0  0.0  0.0  0.0  1.0  0.0  NaN  ...  2.0  0.0  2.0  0.0   
38  NaN  NaN  1.0  NaN  0.0  2.0  2.0  NaN  NaN  0.0  ...  NaN  0.0  1.0  0.0   
39  NaN  0.0  NaN  2.0  0.0  0.0  0.0  NaN  1.0  0.0  ...  0.0  0.0  NaN  NaN   
40  0.0  NaN  2.0  0.0  0.0  1.0  0.0  NaN  0.0  2.0  ...  0.0  NaN  NaN  0.0   
41  NaN  2.0  NaN  0.0  NaN  2.0  2.0  0.0  NaN  NaN  ...  2.0  0.0  2.0  0.0   
42  NaN  0.0  0.0  0.0  NaN  0.0  2.0  0.0  1.0  NaN  ...  2.0  0.0  2.0  1.0   
43  1.0  NaN  NaN  1.0  NaN  0.0  0.0  0.0  NaN  1.0  ...  NaN  NaN  1.0  0.0   
44  1.0  NaN  2.0  2.0  NaN  2.0  NaN  NaN  NaN  0.0  ...  0.0  1.0  0.0  NaN   
45  1.0  0.0  NaN  0.0  NaN  NaN  0.0  0.0  NaN  1.0  ...  0.0  2.0  NaN  NaN   
46  0.0  NaN  NaN  NaN  1.0  1.0  0.0  1.0  NaN  0.0  ...  NaN  0.0  0.0  2.0   
47  0.0  NaN  2.0  NaN  0.0  0.0  0.0  NaN  0.0  2.0  ...  1.0  2.0  2.0  0.0   
48  NaN  NaN  0.0  1.0  1.0  2.0  2.

In [80]:
import numpy as np
import pandas as pd

# Set matrix dimensions and proportions
n = 50
values = np.random.permutation(
    np.concatenate([
        np.full(int(n * n * 0.5), 0),  # 50% 0's
        np.full(int(n * n * 0.25), 1), # 25% 1's
        np.full(int(n * n * 0.25), 2)  # 25% 2's
    ])
)

# Reshape the matrix
R = values.reshape(n, n)

# Create a mask for punching holes with a 30% probability
random_holes = np.random.choice([True, False], size=(n, n), p=[0.3, 0.7])

# Assign NaN to the corresponding positions
R = R.astype(float)  # Convert to float to support NaN
R[random_holes] = np.nan

# Convert to DataFrame
df = pd.DataFrame(R)


print(df)


     0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   0.0  2.0  NaN  NaN  2.0  2.0  NaN  2.0  0.0  NaN  ...  NaN  0.0  2.0  NaN   
1   0.0  NaN  0.0  2.0  0.0  NaN  0.0  1.0  2.0  1.0  ...  0.0  0.0  0.0  0.0   
2   NaN  0.0  NaN  0.0  1.0  1.0  NaN  NaN  NaN  1.0  ...  0.0  1.0  0.0  NaN   
3   NaN  NaN  2.0  2.0  1.0  0.0  NaN  0.0  2.0  NaN  ...  0.0  0.0  0.0  1.0   
4   0.0  1.0  0.0  1.0  2.0  0.0  1.0  0.0  NaN  NaN  ...  NaN  1.0  1.0  NaN   
5   NaN  0.0  NaN  2.0  0.0  0.0  1.0  1.0  2.0  0.0  ...  0.0  0.0  0.0  0.0   
6   NaN  1.0  NaN  0.0  0.0  0.0  1.0  1.0  0.0  2.0  ...  NaN  NaN  2.0  NaN   
7   NaN  NaN  0.0  1.0  2.0  NaN  NaN  2.0  NaN  2.0  ...  2.0  0.0  NaN  NaN   
8   1.0  0.0  NaN  1.0  0.0  NaN  0.0  0.0  0.0  0.0  ...  0.0  2.0  2.0  1.0   
9   1.0  1.0  0.0  NaN  NaN  2.0  NaN  NaN  1.0  0.0  ...  0.0  1.0  2.0  0.0   
10  0.0  NaN  2.0  1.0  2.0  1.0  0.0  NaN  NaN  NaN  ...  0.0  1.0  0.0  NaN   
11  2.0  NaN  0.0  2.0  NaN 

In [81]:
df = pd.DataFrame(R)

col_stats = {
    i: {
        "min" : df.iloc[:, i].min(skipna=True),
        "max" : df.iloc[:, i].max(skipna=True),
        "pct_missing" : df.iloc[:, i].isna().mean(),
        "first_NA" : df.iloc[:, i].isna().idxmax() if df.iloc[:, i].isna().any() else None
        }
        for i in range(df.shape[1])
}

print(col_stats)


{0: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.26, 'first_NA': 2}, 1: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.28, 'first_NA': 1}, 2: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.34, 'first_NA': 0}, 3: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.26, 'first_NA': 0}, 4: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.26, 'first_NA': 9}, 5: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.24, 'first_NA': 1}, 6: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.4, 'first_NA': 0}, 7: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.22, 'first_NA': 2}, 8: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.3, 'first_NA': 2}, 9: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.34, 'first_NA': 0}, 10: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.36, 'first_NA': 0}, 11: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.28, 'first_NA': 4}, 12: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.28, 'first_NA': 2}, 13: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.32, 'first_NA': 3}, 14: {'min': 0.0, 'max': 2.0, 'pct_missing': 0.28, 'first_NA': 2}, 15: {'min': 0.0, 'max

* Set a seed and then create a vector `v` consisting of a sample of 1,000 iid normal realizations with mean -10 and variance 100.

In [83]:
np.random.seed(12)
v = np.random.normal(loc =-10, scale=np.sqrt(100), size = 1000)
print(v)

[-5.27014169e+00 -1.68142588e+01 -7.57560503e+00 -2.70073563e+01
 -2.46857166e+00 -2.53472134e+01 -9.94872922e+00 -1.12022767e+01
 -1.80698188e+01  1.87181939e+01 -1.59782292e+01 -5.27543006e+00
  9.59561180e-01 -2.21516880e+01  3.42356371e+00 -1.12214979e+01
  1.25154770e-01 -1.91386915e+01 -2.02953021e+01  2.09796450e+00
 -4.98127696e+00 -8.61153823e+00 -3.59238887e+00 -4.72667335e+00
 -2.15436024e+01 -3.21333348e+01 -2.68175651e+01 -2.78809425e+01
 -3.21853495e+01 -1.64743078e+01 -1.52840432e+01 -1.03920917e+01
 -7.85024052e+00 -1.38435880e+01 -1.25390408e+01 -9.26747925e+00
 -1.99720384e+01 -1.71385629e+01 -9.64583654e+00 -1.67794537e+01
 -1.57188106e+01 -1.10586232e+01  3.35831339e+00 -6.81334712e+00
 -1.33759525e+01 -1.58526828e+01 -1.11491994e+01  1.24181779e+01
 -4.14741652e+01 -4.64864107e+00 -7.67509561e+00 -1.32388049e+00
 -2.14821271e+01  1.11434424e+01  9.42760690e-03 -1.05141500e+01
 -8.40212302e+00 -1.71626359e+01 -9.49477173e+00 -1.14333741e+01
 -5.64246095e-01 -6.42355

* Repeat this exercise by resetting the seed to ensure you obtain the same results. You can use the random module built in python or random.seed from numpy.

In [85]:
np.random.seed(44)


In [86]:
np.random.seed(12)
v = np.random.normal(loc =-10, scale=np.sqrt(100), size = 1000)
print(v)

[-5.27014169e+00 -1.68142588e+01 -7.57560503e+00 -2.70073563e+01
 -2.46857166e+00 -2.53472134e+01 -9.94872922e+00 -1.12022767e+01
 -1.80698188e+01  1.87181939e+01 -1.59782292e+01 -5.27543006e+00
  9.59561180e-01 -2.21516880e+01  3.42356371e+00 -1.12214979e+01
  1.25154770e-01 -1.91386915e+01 -2.02953021e+01  2.09796450e+00
 -4.98127696e+00 -8.61153823e+00 -3.59238887e+00 -4.72667335e+00
 -2.15436024e+01 -3.21333348e+01 -2.68175651e+01 -2.78809425e+01
 -3.21853495e+01 -1.64743078e+01 -1.52840432e+01 -1.03920917e+01
 -7.85024052e+00 -1.38435880e+01 -1.25390408e+01 -9.26747925e+00
 -1.99720384e+01 -1.71385629e+01 -9.64583654e+00 -1.67794537e+01
 -1.57188106e+01 -1.10586232e+01  3.35831339e+00 -6.81334712e+00
 -1.33759525e+01 -1.58526828e+01 -1.11491994e+01  1.24181779e+01
 -4.14741652e+01 -4.64864107e+00 -7.67509561e+00 -1.32388049e+00
 -2.14821271e+01  1.11434424e+01  9.42760690e-03 -1.05141500e+01
 -8.40212302e+00 -1.71626359e+01 -9.49477173e+00 -1.14333741e+01
 -5.64246095e-01 -6.42355

* Find the average of `v` and the standard error of `v`.

In [88]:
np.mean(v)

-10.116202268301118

In [89]:
standard_error = np.std(v, ddof = 1) / np.sqrt(len(v))
standard_error

0.3246597926662013

* Find the 5%ile of `v` and use the `norm` function from scipy.stats to compute what it theoretically should be. Is the estimate about what is expected by theory?

In [91]:
from scipy.stats import norm

five_percentile_empirical = np.percentile(v, 5)
five_percentile_theoretical = norm.ppf(0.05, loc = -10, scale = 10)

print(f"empirical: {five_percentile_empirical}")
print(f"theoretical: {five_percentile_theoretical}")

empirical: -26.593415498090955
theoretical: -26.44853626951473


Yes the estimate is about expected by theory.

* What is the percentile of `v` that corresponds to the value 0? What should it be theoretically? Is the estimate about what is expected by theory?

In [94]:
percentile_empirical_zero = np.mean(v<=0)

percentile_theoretical_zero = norm.cdf(0, loc = -10, scale = 10) 

print(f"empirical: {percentile_empirical_zero}")    

print(f"theoretical: {percentile_theoretical_zero}")

# Yes, the estimate is about what is expected by theory

empirical: 0.834
theoretical: 0.8413447460685429


* Create a function `my_reverse` which takes as required input a vector `v` and returns the vector in reverse where the first entry is the last entry, etc. No function calls are allowed inside your function otherwise that would defeat the purpose of the exercise! (Yes, there is a base R function that does this called `rev`). 

In [96]:
def my_reverse(vector_v):
    # reversed_vec = np.empty_like(vector_v)
    # n = len(vector_v)
    # for i in range(n):
    #     reversed_vec[i] = vector_v[n-i-1]
    # return reversed_vec
    reversed_vec = []  # Start with an empty array
    for i in range(len(vector_v)):
        reversed_vec.insert(0, vector_v[i])
    return reversed_vec

    # return vector_v[::-1]

print("Head: ", v[:6])
print("Tail: ", my_reverse(v)[-6:])

Head:  [ -5.27014169 -16.81425879  -7.57560503 -27.00735634  -2.46857166
 -25.3472134 ]
Tail:  [-25.34721340208044, -2.4685716605079975, -27.007356340383314, -7.57560503309522, -16.81425879439445, -5.27014168510021]


 * Built in methods in python to reverse a list.

In [98]:
#reverse using slicing
v = [1, 2, 3, 4, 5]
v_reversed = v[::-1]
print(v_reversed)

#using the .reverse method
v = [1, 2, 3, 4, 5]
v.reverse()
print(v)

[5, 4, 3, 2, 1]
[5, 4, 3, 2, 1]


* Create a function `flip_matrix` which takes as required input a matrix, an argument `dim_to_rev` that returns the matrix with the rows in reverse order or the columns in reverse order depending on the `dim_to_rev` argument. Let the default be the dimension of the matrix that is greater.

In [100]:
def flip_matrix(matrix_m, dim_to_rev = None):
    rows, cols = matrix_m.shape

    if dim_to_rev is None:
        dim_to_rev = 0 if rows >= cols else 1

    if dim_to_rev not in [0, 1]:
        raise ValueError("dim_to_rev must be 0 or 1")
    
    if dim_to_rev == 0:
        return matrix_m[::-1, :]
    else:
        return matrix_m[:, ::-1]
    


* Create a list named `my_list` with keys "A", "B", ... where the entries are arrays of size 1, 2 x 2, 3 x 3 x 3, etc. Fill the array with the numbers 1, 2, 3, etc. Make 8 entries according to this sequence.

In [102]:
my_list = {}


for i in range(1, 9):
    shape = tuple([i] * i)  # Generate shape (1,), (2,2), (3,3,3), ...
    my_list[chr(64 + i)] = np.arange(1, np.prod(shape) + 1).reshape(shape)


for key, value in my_list.items():
    print(f"{key}:{value}\n")


A:[1]

B:[[1 2]
 [3 4]]

C:[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

D:[[[[  1   2   3   4]
   [  5   6   7   8]
   [  9  10  11  12]
   [ 13  14  15  16]]

  [[ 17  18  19  20]
   [ 21  22  23  24]
   [ 25  26  27  28]
   [ 29  30  31  32]]

  [[ 33  34  35  36]
   [ 37  38  39  40]
   [ 41  42  43  44]
   [ 45  46  47  48]]

  [[ 49  50  51  52]
   [ 53  54  55  56]
   [ 57  58  59  60]
   [ 61  62  63  64]]]


 [[[ 65  66  67  68]
   [ 69  70  71  72]
   [ 73  74  75  76]
   [ 77  78  79  80]]

  [[ 81  82  83  84]
   [ 85  86  87  88]
   [ 89  90  91  92]
   [ 93  94  95  96]]

  [[ 97  98  99 100]
   [101 102 103 104]
   [105 106 107 108]
   [109 110 111 112]]

  [[113 114 115 116]
   [117 118 119 120]
   [121 122 123 124]
   [125 126 127 128]]]


 [[[129 130 131 132]
   [133 134 135 136]
   [137 138 139 140]
   [141 142 143 144]]

  [[145 146 147 148]
   [149 150 151 152]
   [153 154 155 156]
   [15

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



* Run the following code:

In [104]:
import sys

sizes = {key: sys.getsizeof(value) for key, value in my_list.items()}


# Print the sizes
for key, size in sizes.items():
    print(f"Key: {key}, Size: {size} bytes")

Key: A, Size: 112 bytes
Key: B, Size: 128 bytes
Key: C, Size: 144 bytes
Key: D, Size: 160 bytes
Key: E, Size: 176 bytes
Key: F, Size: 192 bytes
Key: G, Size: 208 bytes
Key: H, Size: 224 bytes


* Create vector `v` consisting of all numbers from -100 to 100 and test using the second line of code

In [106]:
v = np.arange(-100, 101)
v

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,  -79,
        -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,  -68,
        -67,  -66,  -65,  -64,  -63,  -62,  -61,  -60,  -59,  -58,  -57,
        -56,  -55,  -54,  -53,  -52,  -51,  -50,  -49,  -48,  -47,  -46,
        -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,  -35,
        -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,  -24,
        -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,  -13,
        -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,
         -1,    0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
         10,   11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   

* Test the `my_reverse` function using the following code:

In [108]:
# Test the function
v = list(range(1, 11))
v_reversed = my_reverse(v)
print(v)
print(v_reversed)
type(v_reversed)

assert my_reverse(v) == v[::-1], "my_reverse failed for numerical vector"

 # Test with character vector
v_char = ["A", "B", "C"]
assert my_reverse(v_char) == v_char[::-1], "my_reverse failed for character vector"

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


## A little about strings

* Use the `re.split` function by importing the re module and `random` from the random module to put the sentences in the string `lorem` below in random order. You will also need to manipulate the output of `re.split` which is a list. You may need to learn basic concepts of regular expressions.

In [129]:
import re
import random

lorem = """Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Morbi posuere varius volutpat. Morbi faucibus ligula id massa ultricies viverra.
Donec vehicula sagittis nisi non semper. Donec at tempor erat.
Integer dapibus mi lectus, eu posuere arcu ultricies in.
Cras suscipit id nibh lacinia elementum. Curabitur est augue, congue eget quam in, scelerisque semper magna.
Aenean nulla ante, iaculis sed vehicula ac, finibus vel arcu. Mauris at sodales augue."""

split_sentences = re.split(r'(?<=\.)[\s\n]' ,lorem )
random.shuffle(split_sentences)
print(split_sentences)

['Aenean nulla ante, iaculis sed vehicula ac, finibus vel arcu.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Integer dapibus mi lectus, eu posuere arcu ultricies in.', 'Cras suscipit id nibh lacinia elementum.', 'Curabitur est augue, congue eget quam in, scelerisque semper magna.', 'Donec at tempor erat.', 'Morbi posuere varius volutpat.', 'Morbi faucibus ligula id massa ultricies viverra.', 'Donec vehicula sagittis nisi non semper.', 'Mauris at sodales augue.']


* You have a set of names divided by gender (M / F) and generation (Boomer / GenX / Millenial):

M / Boomer      "Theodore, Bernard, Gene, Herbert, Ray, Tom, Lee, Alfred, Leroy, Eddie"

M / GenX        "Marc, Jamie, Greg, Darryl, Tim, Dean, Jon, Chris, Troy, Jeff"

M / Millennial  "Zachary, Dylan, Christian, Wesley, Seth, Austin, Gabriel, Evan, Casey, Luis"

F / Boomer      "Gloria, Joan, Dorothy, Shirley, Betty, Dianne, Kay, Marjorie, Lorraine, Mildred"

F / GenX        "Tracy, Dawn, Tina, Tammy, Melinda, Tamara, Tracey, Colleen, Sherri, Heidi"

F / Millennial  "Samantha, Alexis, Brittany, Lauren, Taylor, Bethany, Latoya, Candice, Brittney, Cheyenne"

Create python dictionary to store this data.


In [112]:
gender_generation = {
    "Male": {
        "Boomer": ["Theodore", "Bernard", "Gene", "Herbert", "Ray", "Tom", "Lee", "Alfred", "Leroy", "Eddie"],
        "GenX": ["Marc", "Jamie", "Greg", "Darryl", "Tim", "Dean", "Jon", "Chris", "Troy", "Jeff"],
        "Millennial": ["Zachary", "Dylan", "Christian", "Wesley", "Seth", "Austin", "Gabriel", "Evan", "Casey", "Luis"]
    },
    "Female": {
        "Boomer": ["Gloria", "Joan", "Dorothy", "Shirley", "Betty", "Dianne", "Kay", "Marjorie", "Lorraine", "Mildred"],
        "GenX": ["Tracy", "Dawn", "Tina", "Tammy", "Melinda", "Tamara", "Tracey", "Colleen", "Sherri", "Heidi"],
        "Millennial": ["Samantha", "Alexis", "Brittany", "Lauren", "Taylor", "Bethany", "Latoya", "Candice", "Brittney", "Cheyenne"]
    }
}


print(gender_generation)

{'Male': {'Boomer': ['Theodore', 'Bernard', 'Gene', 'Herbert', 'Ray', 'Tom', 'Lee', 'Alfred', 'Leroy', 'Eddie'], 'GenX': ['Marc', 'Jamie', 'Greg', 'Darryl', 'Tim', 'Dean', 'Jon', 'Chris', 'Troy', 'Jeff'], 'Millennial': ['Zachary', 'Dylan', 'Christian', 'Wesley', 'Seth', 'Austin', 'Gabriel', 'Evan', 'Casey', 'Luis']}, 'Female': {'Boomer': ['Gloria', 'Joan', 'Dorothy', 'Shirley', 'Betty', 'Dianne', 'Kay', 'Marjorie', 'Lorraine', 'Mildred'], 'GenX': ['Tracy', 'Dawn', 'Tina', 'Tammy', 'Melinda', 'Tamara', 'Tracey', 'Colleen', 'Sherri', 'Heidi'], 'Millennial': ['Samantha', 'Alexis', 'Brittany', 'Lauren', 'Taylor', 'Bethany', 'Latoya', 'Candice', 'Brittney', 'Cheyenne']}}


* Now cleanup the namespace by deleting all stored objects and functions:

In [114]:
import sys


for var in list(globals()):
    if var not in ("__builtins__", "__name__", "__doc__", "__package__"):
        del globals()[var]


print(gender_generation)  


NameError: name 'gender_generation' is not defined